name: Test
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "conda_subchannel/**"
      - "tests/**"
      - "pyproject.toml"
      - "pixi.lock"

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.os }}, py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-latest]
        python-version: ["310", "311", "312", "313"]
    env:
      PIXI_ENV_NAME: test-py${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@28eb668aafebd9dede9d97c4ba1cd9989a4d0004 # v0.9.2
        with:
          environments: ${{ env.PIXI_ENV_NAME }}
      - name: Setup project
        run: |
          pixi run --environment ${{ env.PIXI_ENV_NAME }} dev
      - name: Run tests
        run: pixi run --environment ${{ env.PIXI_ENV_NAME }} test --basetemp=${{ runner.os == 'Windows' && 'D:\\temp' || runner.temp }}
      - name: Build recipe (${{ env.PIXI_ENV_NAME }})
        if: matrix.python-version == '310'
        run: pixi run build

  action:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to deploy to GH Pages automatically
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: ./
        with:
          channel: conda-forge
          keep-trees: python=3.12
          gh-pages-branch: ''  # disable on main
